/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.border.EmptyBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author mynor
 */
public class Principal extends javax.swing.JInternalFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        this.setBorder(new EmptyBorder(0, 0, 0, 0));
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MnVentas = new javax.swing.JMenu();
        MIDetVenta = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        MnDVentas = new javax.swing.JMenu();
        MILimpiarVentas = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        PnlControl = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        btnRealizarVenta = new javax.swing.JButton();
        btnVerVentas = new javax.swing.JButton();
        btnVerCompras = new javax.swing.JButton();
        btnRealizarCompras = new javax.swing.JButton();
        btnNProveedor = new javax.swing.JButton();
        btnVerProveedor = new javax.swing.JButton();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        pnlInventario = new javax.swing.JPanel();
        txtNomProd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBInventario = new rojerusan.RSTableMetro();
        jLabel2 = new javax.swing.JLabel();
        cmbPresentacion = new rojerusan.RSComboMetro();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        lbltitulo2 = new javax.swing.JLabel();
        pnlRVentas = new javax.swing.JPanel();
        btnVender = new javax.swing.JButton();
        btnNuevaVenta = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TBVentas = new rojerusan.RSTableMetro();
        lbltitulo4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTotalVenta = new javax.swing.JTextField();
        txtMontoVenta = new javax.swing.JTextField();
        btnVueltoVenta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblFecha = new rojeru_san.RSLabelFecha();
        pnlVRealizadas = new javax.swing.JPanel();
        lbltitulo1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBVentasRealizas = new rojerusan.RSTableMetro();
        txtNoVenta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        DCFechaVenta = new rojeru_san.componentes.RSDateChooser();
        jLabel15 = new javax.swing.JLabel();
        pnlDVenta = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TBVentasRealizas1 = new rojerusan.RSTableMetro();
        lbltitulo3 = new javax.swing.JLabel();
        txtNoVenta1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        pnlRCompras = new javax.swing.JPanel();
        lbltitulo5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TBVentasRealizas2 = new rojerusan.RSTableMetro();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txaDescripcionCompra = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        pnl5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnl6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnl7 = new javax.swing.JPanel();

        MnVentas.setBackground(new java.awt.Color(0, 51, 51));
        MnVentas.setForeground(new java.awt.Color(255, 255, 255));
        MnVentas.setText("Opciones");
        MnVentas.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        MnVentas.setOpaque(true);

        MIDetVenta.setBackground(new java.awt.Color(0, 51, 51));
        MIDetVenta.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        MIDetVenta.setForeground(new java.awt.Color(255, 255, 255));
        MIDetVenta.setText("Ver Detalle de la venta");
        MIDetVenta.setOpaque(true);
        MIDetVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIDetVentaActionPerformed(evt);
            }
        });
        MnVentas.add(MIDetVenta);

        jPopupMenu1.add(MnVentas);

        MnDVentas.setBackground(new java.awt.Color(0, 51, 51));
        MnDVentas.setForeground(new java.awt.Color(255, 255, 255));
        MnDVentas.setText("Opciones");
        MnDVentas.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        MnDVentas.setOpaque(true);

        MILimpiarVentas.setBackground(new java.awt.Color(0, 51, 51));
        MILimpiarVentas.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        MILimpiarVentas.setForeground(new java.awt.Color(255, 255, 255));
        MILimpiarVentas.setText("Ver Detalle de la venta");
        MILimpiarVentas.setOpaque(true);
        MnDVentas.add(MILimpiarVentas);

        jPopupMenu2.add(MnDVentas);

        setPreferredSize(new java.awt.Dimension(1100, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlControl.setBackground(new java.awt.Color(0, 51, 51));
        PnlControl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        PnlControl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulo.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbltitulo.setText("Aceitera de occidente");
        PnlControl.add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 300, 50));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Home.png"))); // NOI18N
        btnHome.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Inventario</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setSelected(true);
        btnHome.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Home Select.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        PnlControl.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));

        btnAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add user.png"))); // NOI18N
        btnAddUser.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Agregar Nuevo Usuario</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnAddUser.setBorderPainted(false);
        btnAddUser.setContentAreaFilled(false);
        btnAddUser.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add user Select.png"))); // NOI18N
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        PnlControl.add(btnAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 70, 50));

        btnRealizarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/venta.png"))); // NOI18N
        btnRealizarVenta.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Realizar Ventas</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnRealizarVenta.setBorderPainted(false);
        btnRealizarVenta.setContentAreaFilled(false);
        btnRealizarVenta.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Venta Select.png"))); // NOI18N
        btnRealizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarVentaActionPerformed(evt);
            }
        });
        PnlControl.add(btnRealizarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 70, 50));

        btnVerVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VerVentas.png"))); // NOI18N
        btnVerVentas.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Ver Ventas Realizadas</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnVerVentas.setBorderPainted(false);
        btnVerVentas.setContentAreaFilled(false);
        btnVerVentas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VerVentas Select.png"))); // NOI18N
        btnVerVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerVentasActionPerformed(evt);
            }
        });
        PnlControl.add(btnVerVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 70, 50));

        btnVerCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VerVentas.png"))); // NOI18N
        btnVerCompras.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Ver Compras Realizadas</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnVerCompras.setBorderPainted(false);
        btnVerCompras.setContentAreaFilled(false);
        btnVerCompras.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VerVentas Select.png"))); // NOI18N
        btnVerCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerComprasActionPerformed(evt);
            }
        });
        PnlControl.add(btnVerCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 70, 50));

        btnRealizarCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/venta.png"))); // NOI18N
        btnRealizarCompras.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Realizar Compras</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnRealizarCompras.setBorderPainted(false);
        btnRealizarCompras.setContentAreaFilled(false);
        btnRealizarCompras.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Venta Select.png"))); // NOI18N
        btnRealizarCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarComprasActionPerformed(evt);
            }
        });
        PnlControl.add(btnRealizarCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 70, 50));

        btnNProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add user.png"))); // NOI18N
        btnNProveedor.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Agregar Nuevo Proveedor</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnNProveedor.setBorderPainted(false);
        btnNProveedor.setContentAreaFilled(false);
        btnNProveedor.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add user Select.png"))); // NOI18N
        btnNProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNProveedorActionPerformed(evt);
            }
        });
        PnlControl.add(btnNProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 70, 50));

        btnVerProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedores.png"))); // NOI18N
        btnVerProveedor.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Ver Proveedores</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnVerProveedor.setBorderPainted(false);
        btnVerProveedor.setContentAreaFilled(false);
        btnVerProveedor.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedores Select.png"))); // NOI18N
        btnVerProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerProveedorActionPerformed(evt);
            }
        });
        PnlControl.add(btnVerProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 70, 50));

        jPanel1.add(PnlControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 50));

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));

        pnlInventario.setBackground(new java.awt.Color(255, 255, 255));
        pnlInventario.setName("pnlInventario"); // NOI18N
        pnlInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNomProd.setBackground(new java.awt.Color(0, 51, 51));
        txtNomProd.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        txtNomProd.setForeground(new java.awt.Color(255, 255, 255));
        pnlInventario.add(txtNomProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 430, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Presentación:");
        pnlInventario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 150, 40));

        TBInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        TBInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nombre", "Cantidad", "Precio", "Presentación", "Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBInventario.setColorBackgoundHead(new java.awt.Color(0, 51, 51));
        TBInventario.setColorFilasBackgound2(new java.awt.Color(0, 51, 51));
        TBInventario.setColorFilasForeground1(new java.awt.Color(0, 51, 51));
        TBInventario.setColorFilasForeground2(new java.awt.Color(255, 255, 255));
        TBInventario.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        TBInventario.setFuenteFilas(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        TBInventario.setFuenteFilasSelect(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        TBInventario.setFuenteHead(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jScrollPane1.setViewportView(TBInventario);

        pnlInventario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1060, 300));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Descripción del producto");
        pnlInventario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 280, 40));

        cmbPresentacion.setMaximumRowCount(4);
        cmbPresentacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a", "b", "c" }));
        cmbPresentacion.setColorArrow(new java.awt.Color(0, 51, 51));
        cmbPresentacion.setColorBorde(new java.awt.Color(0, 51, 51));
        cmbPresentacion.setColorFondo(new java.awt.Color(0, 51, 51));
        cmbPresentacion.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        pnlInventario.add(cmbPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 330, -1));

        txaDescripcion.setBackground(new java.awt.Color(0, 51, 51));
        txaDescripcion.setColumns(20);
        txaDescripcion.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        txaDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txaDescripcion.setRows(5);
        jScrollPane2.setViewportView(txaDescripcion);

        pnlInventario.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 560, 70));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Producto:");
        pnlInventario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 40));

        lbltitulo2.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        lbltitulo2.setForeground(new java.awt.Color(0, 51, 51));
        lbltitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo2.setText("Inventario");
        pnlInventario.add(lbltitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 40));

        rSPanelsSlider1.add(pnlInventario, "card2");

        pnlRVentas.setBackground(new java.awt.Color(255, 255, 255));
        pnlRVentas.setName("pnlRVentas"); // NOI18N
        pnlRVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Realizar Venta.png"))); // NOI18N
        btnVender.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Finalizar Venta</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnVender.setBorderPainted(false);
        btnVender.setContentAreaFilled(false);
        btnVender.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Realizar Venta Select.png"))); // NOI18N
        pnlRVentas.add(btnVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 430, 70, 50));

        btnNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nueva Venta_Compra.png"))); // NOI18N
        btnNuevaVenta.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Cancelar Venta</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnNuevaVenta.setBorderPainted(false);
        btnNuevaVenta.setContentAreaFilled(false);
        btnNuevaVenta.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nueva Venta_Compra Select.png"))); // NOI18N
        pnlRVentas.add(btnNuevaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 430, 70, 50));

        TBVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        TBVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Presentación", "Proveedor", "Cantidad", "Precio", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBVentas.setColorBackgoundHead(new java.awt.Color(0, 51, 51));
        TBVentas.setColorFilasBackgound2(new java.awt.Color(0, 51, 51));
        TBVentas.setColorFilasForeground1(new java.awt.Color(0, 51, 51));
        TBVentas.setColorFilasForeground2(new java.awt.Color(255, 255, 255));
        TBVentas.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        TBVentas.setFuenteFilas(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        TBVentas.setFuenteFilasSelect(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        TBVentas.setFuenteHead(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jScrollPane4.setViewportView(TBVentas);

        pnlRVentas.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1050, 280));

        lbltitulo4.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        lbltitulo4.setForeground(new java.awt.Color(0, 51, 51));
        lbltitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo4.setText("Realizar ventas");
        pnlRVentas.add(lbltitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1100, 40));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Fecha:");
        pnlRVentas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 40));

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Monto:");
        pnlRVentas.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 80, -1));

        txtTotalVenta.setEditable(false);
        txtTotalVenta.setBackground(new java.awt.Color(0, 51, 51));
        txtTotalVenta.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        txtTotalVenta.setForeground(new java.awt.Color(255, 255, 255));
        pnlRVentas.add(txtTotalVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 220, -1));

        txtMontoVenta.setBackground(new java.awt.Color(0, 51, 51));
        txtMontoVenta.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        txtMontoVenta.setForeground(new java.awt.Color(255, 255, 255));
        pnlRVentas.add(txtMontoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 220, -1));

        btnVueltoVenta.setEditable(false);
        btnVueltoVenta.setBackground(new java.awt.Color(0, 51, 51));
        btnVueltoVenta.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        btnVueltoVenta.setForeground(new java.awt.Color(255, 255, 255));
        pnlRVentas.add(btnVueltoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, 220, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("Total a pagar:");
        pnlRVentas.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 160, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 51));
        jLabel12.setText("Vuelto:");
        pnlRVentas.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 90, -1));

        lblFecha.setForeground(new java.awt.Color(0, 51, 51));
        lblFecha.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        pnlRVentas.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 120, 40));

        rSPanelsSlider1.add(pnlRVentas, "card3");

        pnlVRealizadas.setBackground(new java.awt.Color(255, 255, 255));
        pnlVRealizadas.setName("pnlVRealizadas"); // NOI18N
        pnlVRealizadas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulo1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        lbltitulo1.setForeground(new java.awt.Color(0, 51, 51));
        lbltitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo1.setText("Ventas Realizadas");
        pnlVRealizadas.add(lbltitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 50));

        TBVentasRealizas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        TBVentasRealizas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nombre Usuario", "Fecha", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBVentasRealizas.setColorBackgoundHead(new java.awt.Color(0, 51, 51));
        TBVentasRealizas.setColorFilasBackgound2(new java.awt.Color(0, 51, 51));
        TBVentasRealizas.setColorFilasForeground1(new java.awt.Color(0, 51, 51));
        TBVentasRealizas.setColorFilasForeground2(new java.awt.Color(255, 255, 255));
        TBVentasRealizas.setComponentPopupMenu(jPopupMenu1);
        TBVentasRealizas.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        TBVentasRealizas.setFuenteFilas(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        TBVentasRealizas.setFuenteFilasSelect(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        TBVentasRealizas.setFuenteHead(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jScrollPane3.setViewportView(TBVentasRealizas);

        pnlVRealizadas.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1060, 390));

        txtNoVenta.setBackground(new java.awt.Color(0, 51, 51));
        txtNoVenta.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        txtNoVenta.setForeground(new java.awt.Color(255, 255, 255));
        pnlVRealizadas.add(txtNoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 290, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setText("Fecha:");
        pnlVRealizadas.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 80, -1));

        DCFechaVenta.setBackground(new java.awt.Color(0, 51, 51));
        DCFechaVenta.setForeground(new java.awt.Color(255, 255, 255));
        DCFechaVenta.setColorBackground(new java.awt.Color(0, 51, 51));
        DCFechaVenta.setColorButtonHover(new java.awt.Color(0, 51, 51));
        DCFechaVenta.setColorDiaActual(new java.awt.Color(67, 150, 209));
        DCFechaVenta.setColorForeground(new java.awt.Color(0, 51, 51));
        DCFechaVenta.setColorSelForeground(new java.awt.Color(0, 51, 51));
        DCFechaVenta.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        DCFechaVenta.setFuente(new java.awt.Font("Lucida Calligraphy", 3, 14)); // NOI18N
        pnlVRealizadas.add(DCFechaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 320, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 51));
        jLabel15.setText("No Venta:");
        pnlVRealizadas.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, -1));

        rSPanelsSlider1.add(pnlVRealizadas, "card4");

        pnlDVenta.setBackground(new java.awt.Color(255, 255, 255));
        pnlDVenta.setName("pnl4"); // NOI18N
        pnlDVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("PANEL #4");
        pnlDVenta.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        TBVentasRealizas1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        TBVentasRealizas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Venta", "Nombre producto", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBVentasRealizas1.setColorBackgoundHead(new java.awt.Color(0, 51, 51));
        TBVentasRealizas1.setColorFilasBackgound2(new java.awt.Color(0, 51, 51));
        TBVentasRealizas1.setColorFilasForeground1(new java.awt.Color(0, 51, 51));
        TBVentasRealizas1.setColorFilasForeground2(new java.awt.Color(255, 255, 255));
        TBVentasRealizas1.setComponentPopupMenu(jPopupMenu1);
        TBVentasRealizas1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        TBVentasRealizas1.setFuenteFilas(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        TBVentasRealizas1.setFuenteFilasSelect(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        TBVentasRealizas1.setFuenteHead(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jScrollPane5.setViewportView(TBVentasRealizas1);

        pnlDVenta.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1060, 390));

        lbltitulo3.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        lbltitulo3.setForeground(new java.awt.Color(0, 51, 51));
        lbltitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo3.setText("Detalle de las ventas");
        pnlDVenta.add(lbltitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 50));

        txtNoVenta1.setBackground(new java.awt.Color(0, 51, 51));
        txtNoVenta1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        txtNoVenta1.setForeground(new java.awt.Color(255, 255, 255));
        pnlDVenta.add(txtNoVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 180, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 51));
        jLabel16.setText("No Venta: ");
        pnlDVenta.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 120, -1));

        rSPanelsSlider1.add(pnlDVenta, "card5");

        pnlRCompras.setBackground(new java.awt.Color(255, 255, 255));
        pnlRCompras.setName("pnlRCompras"); // NOI18N
        pnlRCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulo5.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        lbltitulo5.setForeground(new java.awt.Color(0, 51, 51));
        lbltitulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo5.setText("Realizar Compras");
        pnlRCompras.add(lbltitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 50));

        TBVentasRealizas2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        TBVentasRealizas2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nombre Usuario", "Fecha", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBVentasRealizas2.setColorBackgoundHead(new java.awt.Color(0, 51, 51));
        TBVentasRealizas2.setColorFilasBackgound2(new java.awt.Color(0, 51, 51));
        TBVentasRealizas2.setColorFilasForeground1(new java.awt.Color(0, 51, 51));
        TBVentasRealizas2.setColorFilasForeground2(new java.awt.Color(255, 255, 255));
        TBVentasRealizas2.setComponentPopupMenu(jPopupMenu1);
        TBVentasRealizas2.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        TBVentasRealizas2.setFuenteFilas(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        TBVentasRealizas2.setFuenteFilasSelect(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        TBVentasRealizas2.setFuenteHead(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jScrollPane6.setViewportView(TBVentasRealizas2);

        pnlRCompras.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 700, 300));

        jLabel17.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 51));
        jLabel17.setText("Descripción:");
        pnlRCompras.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 150, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 51));
        jLabel18.setText("Detalle de la presentación: ");
        pnlRCompras.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 300, -1));

        jLabel19.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 51));
        jLabel19.setText("Cantidad:");
        pnlRCompras.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, -1));

        jLabel20.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 51));
        jLabel20.setText("Costo:");
        pnlRCompras.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, -1));

        jLabel21.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 51, 51));
        jLabel21.setText("Precio:");
        pnlRCompras.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 110, -1));

        txaDescripcionCompra.setBackground(new java.awt.Color(0, 51, 51));
        txaDescripcionCompra.setColumns(20);
        txaDescripcionCompra.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        txaDescripcionCompra.setForeground(new java.awt.Color(255, 255, 255));
        txaDescripcionCompra.setRows(5);
        jScrollPane7.setViewportView(txaDescripcionCompra);

        pnlRCompras.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 310, 70));

        jLabel23.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 51));
        jLabel23.setText("Código:");
        pnlRCompras.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, -1));

        jLabel24.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 51, 51));
        jLabel24.setText("Presentación:");
        pnlRCompras.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, -1));

        jLabel25.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 51));
        jLabel25.setText("Proveedor:");
        pnlRCompras.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, -1));

        rSPanelsSlider1.add(pnlRCompras, "card5");

        pnl5.setBackground(new java.awt.Color(255, 255, 255));
        pnl5.setName("pnl2"); // NOI18N
        pnl5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PANEL #5");
        pnl5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        rSPanelsSlider1.add(pnl5, "card3");

        pnl6.setBackground(new java.awt.Color(255, 255, 255));
        pnl6.setName("pnl2"); // NOI18N
        pnl6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PANEL #6");
        pnl6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        rSPanelsSlider1.add(pnl6, "card3");

        pnl7.setBackground(new java.awt.Color(255, 255, 255));
        pnl7.setName("pnl2"); // NOI18N
        pnl7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        rSPanelsSlider1.add(pnl7, "card3");

        jPanel1.add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1100, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarVentaActionPerformed
        if (!this.btnRealizarVenta.isSelected()) {
            this.btnHome.setSelected(false);
            this.btnRealizarVenta.setSelected(true);
            this.btnVerVentas.setSelected(false);
            this.btnRealizarCompras.setSelected(false);
            this.btnVerCompras.setSelected(false);
            this.btnNProveedor.setSelected(false);
            this.btnVerProveedor.setSelected(false);
            this.btnAddUser.setSelected(false);
            rSPanelsSlider1.setPanelSlider(20, pnlRVentas, RSPanelsSlider.DIRECT.LEFT);
        }
    }//GEN-LAST:event_btnRealizarVentaActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        if (!this.btnHome.isSelected()) {
            this.btnHome.setSelected(true);
            this.btnRealizarVenta.setSelected(false);
            this.btnVerVentas.setSelected(false);
            this.btnRealizarCompras.setSelected(false);
            this.btnVerCompras.setSelected(false);
            this.btnNProveedor.setSelected(false);
            this.btnVerProveedor.setSelected(false);
            this.btnAddUser.setSelected(false);
            rSPanelsSlider1.setPanelSlider(20, pnlInventario, RSPanelsSlider.DIRECT.LEFT);
        }
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnVerVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerVentasActionPerformed
        if (!this.btnVerVentas.isSelected()) {
            this.btnHome.setSelected(false);
            this.btnRealizarVenta.setSelected(false);
            this.btnVerVentas.setSelected(true);
            this.btnRealizarCompras.setSelected(false);
            this.btnVerCompras.setSelected(false);
            this.btnNProveedor.setSelected(false);
            this.btnVerProveedor.setSelected(false);
            this.btnAddUser.setSelected(false);
            rSPanelsSlider1.setPanelSlider(20, pnlVRealizadas, RSPanelsSlider.DIRECT.LEFT);
        }

    }//GEN-LAST:event_btnVerVentasActionPerformed

    private void btnVerComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerComprasActionPerformed
        rSPanelsSlider1.setPanelSlider(20, pnlRCompras, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnVerComprasActionPerformed

    private void btnRealizarComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarComprasActionPerformed
        if (!this.btnVerVentas.isSelected()) {
            this.btnHome.setSelected(false);
            this.btnRealizarVenta.setSelected(false);
            this.btnVerVentas.setSelected(false);
            this.btnRealizarCompras.setSelected(true);
            this.btnVerCompras.setSelected(false);
            this.btnNProveedor.setSelected(false);
            this.btnVerProveedor.setSelected(false);
            this.btnAddUser.setSelected(false);
            rSPanelsSlider1.setPanelSlider(20, pnlRCompras, RSPanelsSlider.DIRECT.LEFT);
        }

    }//GEN-LAST:event_btnRealizarComprasActionPerformed

    private void btnNProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNProveedorActionPerformed
        rSPanelsSlider1.setPanelSlider(20, pnl6, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnNProveedorActionPerformed

    private void btnVerProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProveedorActionPerformed
        rSPanelsSlider1.setPanelSlider(20, pnl7, RSPanelsSlider.DIRECT.LEFT);

    }//GEN-LAST:event_btnVerProveedorActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        if (!this.btnAddUser.isSelected()) {
            this.btnHome.setSelected(false);
            this.btnRealizarVenta.setSelected(false);
            this.btnVerVentas.setSelected(false);
            this.btnRealizarCompras.setSelected(false);
            this.btnVerCompras.setSelected(false);
            this.btnNProveedor.setSelected(false);
            this.btnVerProveedor.setSelected(false);
            this.btnAddUser.setSelected(true);
            new Registro().setVisible(true);
        }
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void MIDetVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIDetVentaActionPerformed
        rSPanelsSlider1.setPanelSlider(20, pnlDVenta, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_MIDetVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.componentes.RSDateChooser DCFechaVenta;
    private javax.swing.JMenuItem MIDetVenta;
    private javax.swing.JMenuItem MILimpiarVentas;
    private javax.swing.JMenu MnDVentas;
    private javax.swing.JMenu MnVentas;
    private javax.swing.JPanel PnlControl;
    private rojerusan.RSTableMetro TBInventario;
    private rojerusan.RSTableMetro TBVentas;
    private rojerusan.RSTableMetro TBVentasRealizas;
    private rojerusan.RSTableMetro TBVentasRealizas1;
    private rojerusan.RSTableMetro TBVentasRealizas2;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnNProveedor;
    private javax.swing.JButton btnNuevaVenta;
    private javax.swing.JButton btnRealizarCompras;
    private javax.swing.JButton btnRealizarVenta;
    private javax.swing.JButton btnVender;
    private javax.swing.JButton btnVerCompras;
    private javax.swing.JButton btnVerProveedor;
    private javax.swing.JButton btnVerVentas;
    private javax.swing.JTextField btnVueltoVenta;
    private rojerusan.RSComboMetro cmbPresentacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private rojeru_san.RSLabelFecha lblFecha;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lbltitulo1;
    private javax.swing.JLabel lbltitulo2;
    private javax.swing.JLabel lbltitulo3;
    private javax.swing.JLabel lbltitulo4;
    private javax.swing.JLabel lbltitulo5;
    private javax.swing.JPanel pnl5;
    private javax.swing.JPanel pnl6;
    private javax.swing.JPanel pnl7;
    private javax.swing.JPanel pnlDVenta;
    private javax.swing.JPanel pnlInventario;
    private javax.swing.JPanel pnlRCompras;
    private javax.swing.JPanel pnlRVentas;
    private javax.swing.JPanel pnlVRealizadas;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private javax.swing.JTextArea txaDescripcion;
    private javax.swing.JTextArea txaDescripcionCompra;
    private javax.swing.JTextField txtMontoVenta;
    private javax.swing.JTextField txtNoVenta;
    private javax.swing.JTextField txtNoVenta1;
    private javax.swing.JTextField txtNomProd;
    private javax.swing.JTextField txtTotalVenta;
    // End of variables declaration//GEN-END:variables
}
