/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Usuario;
import com.sun.awt.AWTUtilities;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Shape;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JTextField;
import org.apache.commons.codec.digest.DigestUtils;
import rojerusan.RSNotifyAnimated;

/**
 *
 * @author mynor
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        user = new Usuario();
        this.setUndecorated(true);
        initComponents();
        cmbPuestos.setModel(user.puestos());
        this.setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 27, 27);
        AWTUtilities.setWindowShape(this, forma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        PssConfirContrasenia = new javax.swing.JPasswordField();
        PssContrasenia = new javax.swing.JPasswordField();
        RBSi = new javax.swing.JRadioButton();
        RBNo = new javax.swing.JRadioButton();
        cmbPuestos = new rojerusan.RSComboMetro();
        btnInsertar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 100, 20));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 100, 20));

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No telefono:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 130, 20));

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 130, 20));

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Confirmar Contraseña:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 260, 20));

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Puesto:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 80, 20));

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Registrar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 160, 40));

        jLabel11.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Activo:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 90, 20));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Lucida Calligraphy", 3, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 51, 51));
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 300, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Lucida Calligraphy", 3, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 51, 51));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 330, -1));

        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido.setFont(new java.awt.Font("Lucida Calligraphy", 3, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(0, 51, 51));
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 330, -1));

        PssConfirContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        PssConfirContrasenia.setFont(new java.awt.Font("Lucida Calligraphy", 3, 14)); // NOI18N
        PssConfirContrasenia.setForeground(new java.awt.Color(0, 51, 51));
        PssConfirContrasenia.setText("jPasswordField1");
        PssConfirContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PssConfirContraseniaKeyTyped(evt);
            }
        });
        jPanel1.add(PssConfirContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 300, -1));

        PssContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        PssContrasenia.setFont(new java.awt.Font("Lucida Calligraphy", 3, 14)); // NOI18N
        PssContrasenia.setForeground(new java.awt.Color(0, 51, 51));
        PssContrasenia.setText("jPasswordField1");
        PssContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PssContraseniaKeyTyped(evt);
            }
        });
        jPanel1.add(PssContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 300, -1));

        RBSi.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(RBSi);
        RBSi.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        RBSi.setForeground(new java.awt.Color(255, 255, 255));
        RBSi.setSelected(true);
        RBSi.setText("Si");
        RBSi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RBSiKeyTyped(evt);
            }
        });
        jPanel1.add(RBSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 60, -1));

        RBNo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(RBNo);
        RBNo.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        RBNo.setForeground(new java.awt.Color(255, 255, 255));
        RBNo.setText("No");
        RBNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RBNoKeyTyped(evt);
            }
        });
        jPanel1.add(RBNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 60, -1));

        cmbPuestos.setBackground(new java.awt.Color(255, 255, 255));
        cmbPuestos.setMaximumRowCount(4);
        cmbPuestos.setColorArrow(new java.awt.Color(0, 51, 51));
        cmbPuestos.setColorBorde(new java.awt.Color(255, 255, 255));
        cmbPuestos.setColorFondo(new java.awt.Color(0, 51, 51));
        cmbPuestos.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jPanel1.add(cmbPuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 320, -1));

        btnInsertar.setBackground(new java.awt.Color(255, 255, 255));
        btnInsertar.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        btnInsertar.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkmark.png"))); // NOI18N
        btnInsertar.setBorderPainted(false);
        btnInsertar.setContentAreaFilled(false);
        btnInsertar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Checkmark Select.png"))); // NOI18N
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 50, 40));

        jLabel12.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cancelar");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 150, 40));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar.png"))); // NOI18N
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar Select.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 50, 40));

        jLabel13.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Registrar");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 150, 40));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar Select.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 60, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        if (verificar()) {
            String contrasenia = DigestUtils.md5Hex(PssContrasenia.getText());

            boolean activo = RBSi.isSelected();
            int id = cmbPuestos.getSelectedIndex() + 1;
            if (user.insertarUsuario(txtNombre.getText(), txtApellido.getText(), txtUsuario.getText(),
                    contrasenia, activo, id)) {
                new rojerusan.RSNotifyAnimated("¡Correcto!", "Usuario ingresado correctamente",
                        5, RSNotifyAnimated.PositionNotify.BottomLeft, RSNotifyAnimated.AnimationNotify.BottomUp,
                        RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
                this.dispose();
            } else {
                new rojerusan.RSNotifyAnimated("¡ERROR!", "Usuario no ingresado correctamente.",
                        5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp,
                        RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
            }
        } else {
            new rojerusan.RSNotifyAnimated("¡ERROR!", "Usuario no ingresado correctamente.\nVerifique los campos",
                    5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp,
                    RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        Point p = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(p.x - x, p.y - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed

    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        Letras(evt, txtApellido);
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        Letras(evt, txtUsuario);
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        if (evt.getKeyChar() == 10) {
            PssContrasenia.setText("");
            PssContrasenia.requestFocus();
        }
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void PssContraseniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PssContraseniaKeyTyped
        if (evt.getKeyChar() == 10) {
            PssConfirContrasenia.setText("");
            PssConfirContrasenia.requestFocus();
        }
    }//GEN-LAST:event_PssContraseniaKeyTyped

    private void PssConfirContraseniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PssConfirContraseniaKeyTyped
        if (evt.getKeyChar() == 10) {
            RBSi.requestFocus();
        }
    }//GEN-LAST:event_PssConfirContraseniaKeyTyped

    private void RBSiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RBSiKeyTyped
        if (evt.getKeyChar() == 10) {
            RBSi.setSelected(true);
            RBNo.requestFocus();
        }
    }//GEN-LAST:event_RBSiKeyTyped

    private void RBNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RBNoKeyTyped
        if (evt.getKeyChar() == 10) {
            RBNo.setSelected(true);
            cmbPuestos.requestFocus();
        }
    }//GEN-LAST:event_RBNoKeyTyped

    private void Letras(KeyEvent e, JTextField txt) {
        if ((e.getKeyChar() < 'a' || e.getKeyChar() > 'z') && (e.getKeyChar() < 'A' || e.getKeyChar() > 'Z')) {
            if (e.getKeyChar() == 10) {
                txt.requestFocus();
            } else {
                e.consume();
            }
        }
    }

    private boolean verificar() {
        if (txtNombre.getText().length() == 0) {
            return false;
        } else if (txtApellido.getText().length() == 0) {
            return false;
        } else if (txtUsuario.getText().length() == 0) {
            return false;
        } else if (PssContrasenia.getText().length() == 0) {
            return false;
        } else if (PssConfirContrasenia.getText().length() == 0) {
            return false;
        } else {
            return PssConfirContrasenia.getText().equals(PssContrasenia.getText());
        }
    }

    private final Usuario user;
    private int x, y;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PssConfirContrasenia;
    private javax.swing.JPasswordField PssContrasenia;
    private javax.swing.JRadioButton RBNo;
    private javax.swing.JRadioButton RBSi;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.ButtonGroup buttonGroup1;
    private rojerusan.RSComboMetro cmbPuestos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
