/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author mynor
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 27, 27);
        AWTUtilities.setWindowShape(this, forma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        PssConfirContrasenia = new javax.swing.JPasswordField();
        PssContrasenia = new javax.swing.JPasswordField();
        RBSi = new javax.swing.JRadioButton();
        RBNo = new javax.swing.JRadioButton();
        rSComboMetro1 = new rojerusan.RSComboMetro();
        txtOtroPuesto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, 20));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 100, 20));

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 100, 20));

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, 20));

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Confirmar Contraseña:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 260, 20));

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Puesto:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 80, 20));

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Registrar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 160, 40));

        jLabel11.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Activo:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 90, 20));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Lucida Calligraphy", 3, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 330, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Lucida Calligraphy", 3, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 330, -1));

        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido.setFont(new java.awt.Font("Lucida Calligraphy", 3, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 330, -1));

        PssConfirContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        PssConfirContrasenia.setFont(new java.awt.Font("Lucida Calligraphy", 3, 14)); // NOI18N
        PssConfirContrasenia.setForeground(new java.awt.Color(0, 51, 51));
        PssConfirContrasenia.setText("jPasswordField1");
        jPanel1.add(PssConfirContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 300, -1));

        PssContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        PssContrasenia.setFont(new java.awt.Font("Lucida Calligraphy", 3, 14)); // NOI18N
        PssContrasenia.setForeground(new java.awt.Color(0, 51, 51));
        PssContrasenia.setText("jPasswordField1");
        jPanel1.add(PssContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 300, -1));

        RBSi.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(RBSi);
        RBSi.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        RBSi.setForeground(new java.awt.Color(255, 255, 255));
        RBSi.setText("Si");
        jPanel1.add(RBSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 60, -1));

        RBNo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(RBNo);
        RBNo.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        RBNo.setForeground(new java.awt.Color(255, 255, 255));
        RBNo.setText("No");
        jPanel1.add(RBNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 60, -1));

        rSComboMetro1.setBackground(new java.awt.Color(255, 255, 255));
        rSComboMetro1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rSComboMetro1.setMaximumRowCount(4);
        rSComboMetro1.setColorArrow(new java.awt.Color(0, 51, 51));
        rSComboMetro1.setColorBorde(new java.awt.Color(255, 255, 255));
        rSComboMetro1.setColorFondo(new java.awt.Color(0, 51, 51));
        rSComboMetro1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jPanel1.add(rSComboMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 320, -1));

        txtOtroPuesto.setEditable(false);
        txtOtroPuesto.setBackground(new java.awt.Color(255, 255, 255));
        txtOtroPuesto.setFont(new java.awt.Font("Lucida Calligraphy", 3, 14)); // NOI18N
        txtOtroPuesto.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(txtOtroPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 320, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkmark.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Checkmark Select.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 50, 40));

        jLabel12.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cabcelar");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 150, 40));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar.png"))); // NOI18N
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar Select.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 50, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Registrar");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 150, 40));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar Select.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 60, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Registro reg = new Registro();
        reg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        Login p =new Login();
        p.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PssConfirContrasenia;
    private javax.swing.JPasswordField PssContrasenia;
    private javax.swing.JRadioButton RBNo;
    private javax.swing.JRadioButton RBSi;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private rojerusan.RSComboMetro rSComboMetro1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOtroPuesto;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
